name: Magisk DiagGrab Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/main.yml"

jobs:
  build-diaggrab:
    name: Build Magisk DiagGrab
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v6

      - name: Clone official Magisk
        run: |
          git clone --recursive https://github.com/topjohnwu/Magisk.git

      - name: Fix submodules
        run: |
          cd Magisk
          git submodule deinit -f .
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install correct NDK
        run: |
          cd Magisk
          python3 build.py ndk

      - name: Patch package name
        run: |
          cd Magisk
          export LC_ALL=C
          OLD="com.topjohnwu.magisk"
          NEW="com.simcom.diaggrab"

          find . -name "AndroidManifest.xml" -print0 | xargs -0 sed -i "s/$OLD/$NEW/g"
          find . -type f \( -name "*.kt" -o -name "*.java" \) -print0 | xargs -0 sed -i "s/$OLD/$NEW/g"
          find native -type f -print0 | xargs -0 sed -i "s/$OLD/$NEW/g"

          if [ -d app/src/main/java/com/topjohnwu ]; then
            mkdir -p app/src/main/java/com/simcom/diaggrab
            rsync -a app/src/main/java/com/topjohnwu/magisk/ app/src/main/java/com/simcom/diaggrab/
            rm -rf app/src/main/java/com/topjohnwu
          fi

          if [ -d app/stub/src/main/java/com/topjohnwu ]; then
            mkdir -p app/stub/src/main/java/com/simcom/diaggrab
            rsync -a app/stub/src/main/java/com/topjohnwu/magisk/ app/stub/src/main/java/com/simcom/diaggrab/
            rm -rf app/stub/src/main/java/com/topjohnwu
          fi

          find . -type f -print0 | xargs -0 sed -i "s/$OLD.BuildConfig/$NEW.BuildConfig/g"

      - name: Build release
        run: cd Magisk && python3 build.py -vr all

      - name: Build debug
        run: cd Magisk && python3 build.py -v all

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: diaggrab-${{ github.sha }}
          path: Magisk/out
